# This workflow will do a clean install of node dependencies, cache/restore them and build the source code

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - name: Deploy to https://docs.flux.industries
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        ftp_host: ${{ secrets.SERVER_IP }}
        ftp_username: ${{ secrets.SERVER_USERNAME }}
        ftp_password: ${{ secrets.SERVER_PASSWORD }}
        local_source_dir: 'build'
        dist_target_dir: '/docs'
        delete: 'true'
